Repository openimsdk/protocol, pull requests merged in 2023-12, with the labels that each got.

#41 update protocol for pinfriend and fix bug
  friend/friend.go
  friend/friend.pb.go
  friend/friend.proto
  group/group.go
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
  user/user.go
  user/user.pb.go
  user/user.proto
Labels: size/M

#42 remove ”remove user"
  user/user.go
  user/user.pb.go
  user/user.proto
Labels: size/S

#43 Add processUserCommand and pinFriend
  friend/friend.go
  user/user.go
  user/user.pb.go
  user/user.proto
Labels: size/L

#45 update user command
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
  user/user.pb.go
  user/user.proto
Labels: size/S

#46 add and fix ex field
  friend/friend.pb.go
  friend/friend.proto
  group/group.pb.go
  group/group.proto
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
  user/user.pb.go
  user/user.proto
Labels: size/S

#47 update updateUserInfoEx
  friend/friend.go
  friend/friend.pb.go
  friend/friend.proto
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
  user/user.pb.go
  user/user.proto
Labels: size/S

#49 feat: add Notification methods
  constant/constant.go
  user/user.go
  user/user.pb.go
  user/user.proto
Labels: size/M

#51 fix: fix the searchNotificationReq
  user/user.pb.go
  user/user.proto
Labels: size/XS

#48 update user nickname check
  constant/constant.go
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
  user/user.go
  user/user.pb.go
Labels: size/S

#50 feat: getConversation api
  conversation/conversation.go
  conversation/conversation.pb.go
  conversation/conversation.proto
  msg/msg.go
  msg/msgv3.pb.go
  msg/msgv3.proto
  sdkws/sdkws.go
  third/third.go
  user/user.pb.go
Labels: size/L

#54 del some check method
  msg/msg.go
  sdkws/sdkws.go
Labels: size/M

#55 update userInfoExReq
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
Labels: size/XS
