Repository openimsdk/protocol, pull requests merged in 2024-10, with the labels that each got.

#147 feat: login policy
  constant/constant.go
Labels: size/XS

#148 feat: platform class
  constant/platform_id_to_name.go
Labels: size/M

#149 feat: kick tokens
  auth/auth.pb.go
  auth/auth.proto
Labels: size/XS

#150 fix: joinSource check args error.
  group/group.go
Labels: size/XS

#151 fix:remove AddApplicationVersion
  third/third.pb.go
  third/third.proto
Labels: size/S

#152 fix:remove unused method.
  third/third.pb.go
  third/third.proto
Labels: size/M

#153 fix: remove check.
  third/third.go
Labels: size/S
