Repository openimsdk/protocol, pull requests merged in 2024-09, with the labels that each got.

#118 feat: implement request max count limit.
  .github/code-language-detector.yml
  .github/workflows/code-language-detector.yml
  .github/workflows/comment-check.yml
  group/group.go
  relation/relation.go
Labels: size/L

#119 Add apilimit
  constant/limit.go
  group/group.go
  relation/relation.go
Labels: size/S

#120 feat: change GetUserStatus userIDs limit
  user/user.go
Labels: size/XS

#121 feat: add PushMsgReq
  auth/auth.pb.go
  conversation/conversation.pb.go
  errinfo/errinfo.pb.go
  group/group.go
  group/group.pb.go
  msg/msg.pb.go
  msggateway/msggateway.pb.go
  push/push.pb.go
  push/push.proto
  relation/relation.pb.go
  rtc/rtc.pb.go
  sdkws/sdkws.pb.go
  statistics/statistics.pb.go
  third/third.pb.go
  user/user.pb.go
  wrapperspb/wrapperspb.pb.go
Labels: size/M

#123 update
  group/group.go
Labels: size/M

#124 feat: get all online users
  user/user.pb.go
  user/user.proto
Labels: size/S

#125 update SearchMessage response.
  msg/msg.pb.go
  msg/msg.proto
Labels: size/XS

#126 v0.0.72-alpha.20
  msg/msg.pb.go
  msg/msg.proto
Labels: size/XS

#127 Update groupInfoex field to standard.
  group/group.pb.go
  group/group.proto
Labels: size/XS

#128 update SetGroupInfoEx
  group/group.pb.go
  group/group.proto
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
Labels: size/S

#129 Update groupInfoex field name to standard
  group/group.pb.go
  group/group.proto
Labels: size/XS

#130 update setGroupInfoEx field.
  group/group.pb.go
  group/group.proto
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
Labels: size/S

#131 feat: update userRegister field.
  user/user.pb.go
  user/user.proto
Labels: size/L

#132 feat: add getSpecifiedBlacks interface.
  relation/relation.pb.go
  relation/relation.proto
Labels: size/M

#133 feat: GetNotNotifyConversationIDs
  conversation/conversation.pb.go
  conversation/conversation.proto
Labels: size/XS

#134 feat: GetSpecifiedUserGroupRequestInfo
  group/group.pb.go
  group/group.proto
Labels: size/S

#135 feat: GetPinnedConversationIDs
  conversation/conversation.pb.go
  conversation/conversation.proto
Labels: size/S

#136 feat: change platformID
  msggateway/msggateway.pb.go
  msggateway/msggateway.proto
Labels: size/XS

#137 feat: change platformID
  msggateway/msggateway.pb.go
  msggateway/msggateway.proto
Labels: size/XS

#138 remove unused fields.
  auth/auth.pb.go
  conversation/conversation.pb.go
  errinfo/errinfo.pb.go
  group/group.pb.go
  msg/msg.pb.go
  msggateway/msggateway.pb.go
  msggateway/msggateway.proto
  push/push.pb.go
  relation/relation.pb.go
  rtc/rtc.pb.go
  sdkws/sdkws.pb.go
  statistics/statistics.pb.go
  third/third.pb.go
  user/user.pb.go
  user/user.proto
  wrapperspb/wrapperspb.pb.go
Labels: size/M

#139 update constant.
  constant/constant.go
Labels: size/S

#140 update fields.
  constant/constant.go
  user/user.pb.go
  user/user.proto
Labels: size/XS

#141 update const
  constant/constant.go
Labels: size/XS

#142 update userToken field
  auth/auth.pb.go
  auth/auth.proto
Labels: size/M

#143 UserToken
  auth/auth.go
Labels: size/XS

#146 fix check
  auth/auth.go
Labels: size/XS
