Repository openimsdk/protocol, pull requests merged in 2024-06, with the labels that each got.

#73 feat:friend-apply-incremental-pb
  auth/auth.pb.go
  conversation/conversation.pb.go
  errinfo/errinfo.pb.go
  group/group.pb.go
  msg/msg.pb.go
  msggateway/msggateway.pb.go
  push/push.pb.go
  relation/relation.pb.go
  relation/relation.proto
  rtc/rtc.pb.go
  sdkws/sdkws.pb.go
  statistics/statistics.pb.go
  third/third.pb.go
  user/user.pb.go
  wrapperspb/wrapperspb.pb.go
Labels: size/S

#75 fix:incremental-friend
  relation/relation.pb.go
  relation/relation.proto
Labels: size/S

#76 fix:only one can create group
  group/group.go
Labels: size/XS

#78 fix:only one can create group
  group/group.go
Labels: size/XS

#80 fix:no faceURL error return
  user/user.go
Labels: size/XS

#81 Feat：get full friend ids and refector
  group/group.go
  group/group.pb.go
  group/group.proto
  relation/relation.go
  relation/relation.pb.go
  relation/relation.proto
Labels: size/M

#82 Feat friend version return
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
Labels: size/XS

#83 add DeleteOutdatedData service in third
  third/third.pb.go
  third/third.proto
Labels: size/M

#84 update DeleteOutDatedData field attribute.
  third/third.pb.go
  third/third.proto
Labels: size/XS

#85 Revert "update DeleteOutDatedData field attribute."
  third/third.pb.go
  third/third.proto
Labels: size/XS
