Repository openimsdk/protocol, pull requests merged in 2024-11, with the labels that each got.

#154 feat: platform class
  constant/platform_id_to_name.go
Labels: size/XS

#155 feat: platform class
  constant/platform_id_to_name.go
Labels: size/XS

#156 feat: platform class
  constant/constant.go
Labels: size/XS

#158 build: update protoc generate to latest type.
  README.md
  gen.cmd
  gen.sh
  gen_openmeeting.sh
Labels: size/M

#159 build: update grpc and protobuf pkg.
  go.mod
  go.sum
Labels: size/M

#160 fix: solve grpc generate.
  gen.cmd
  gen.sh
  gen_openmeeting.sh
Labels: size/M

#161 fix: improve third method.
  auth/auth.pb.go
  auth/auth_grpc.pb.go
  conversation/conversation.pb.go
  conversation/conversation_grpc.pb.go
  errinfo/errinfo.pb.go
  group/group.pb.go
  group/group_grpc.pb.go
  jssdk/jssdk.pb.go
  msg/msg.pb.go
  msg/msg_grpc.pb.go
  msggateway/msggateway.pb.go
  msggateway/msggateway_grpc.pb.go
  push/push.pb.go
  push/push_grpc.pb.go
  relation/relation.pb.go
  relation/relation_grpc.pb.go
  rtc/rtc.pb.go
  rtc/rtc_grpc.pb.go
  sdkws/sdkws.pb.go
  statistics/statistics.pb.go
  third/third.pb.go
  third/third.proto
  third/third_grpc.pb.go
  user/user.pb.go
  user/user_grpc.pb.go
  wrapperspb/wrapperspb.pb.go
Labels: size/XS

#162 fix: add deleteObjectType fields.
  third/third.pb.go
  third/third.proto
Labels: size/XS

#163 Update pb
  auth/auth.pb.go
  auth/auth_grpc.pb.go
  conversation/conversation.pb.go
  conversation/conversation_grpc.pb.go
  errinfo/errinfo.pb.go
  gen.cmd
  group/group.pb.go
  group/group_grpc.pb.go
  jssdk/jssdk.pb.go
  msg/msg.pb.go
  msg/msg_grpc.pb.go
  msggateway/msggateway.pb.go
  msggateway/msggateway_grpc.pb.go
  push/push.pb.go
  push/push_grpc.pb.go
  relation/relation.pb.go
  relation/relation_grpc.pb.go
  rtc/rtc.pb.go
  rtc/rtc_grpc.pb.go
  sdkws/sdkws.pb.go
  statistics/statistics.pb.go
  third/third.pb.go
  third/third_grpc.pb.go
  user/user.pb.go
  user/user_grpc.pb.go
  wrapperspb/wrapperspb.pb.go
Labels: size/S
