Repository openimsdk/protocol, pull requests merged in 2024-07, with the labels that each got.

#86 Fix user id check
  user/user.go
  util/datautil/string.go
Labels: size/M

#87 feature: add display read field
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
Labels: size/XS

#88 Feature group msg read
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
Labels: size/XS

#89 feature: add display read field
  constant/group.go
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
Labels: size/S

#90 feature: check
  constant/group.go
  group/group.go
Labels: size/S

#91 fix: check user id
  user/user.go
Labels: size/XS

#92 fix: remove group read
  constant/group.go
  group/group.go
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
Labels: size/S

#93 feat: add BatchGetIncrementalGroupMember service.
  group/group.pb.go
  group/group.proto
Labels: size/L

#94 fix: update uncorrect message name.
  group/group.pb.go
  group/group.proto
Labels: size/XS

#95 feat:implement rpc format method
  conversation/conversation.go
  group/group.go
  msg/msg.go
  user/user.go
Labels: size/M

#96 implement format method in pb.
  group/group.go
  msg/msg.go
  msg/msg.proto
  relation/relation.go
Labels: size/L

#97 implement format method in pb.
  conversation/conversation.go
  group/group.go
  relation/relation.go
Labels: size/S

#98 update format in group module.
  group/group.go
Labels: size/XS

#99 feat: update format method in get all conversations.
  conversation/conversation.go
Labels: size/XS

#100 feat: update max Seq format method.
  sdkws/sdkws.go
Labels: size/S

#101 update Format method in pb.
  conversation/conversation.go
  group/group.go
  relation/relation.go
  user/user.go
Labels: size/S

#102 update format method in pb.
  constant/constant.go
  group/group.go
  relation/relation.go
  user/user.go
Labels: size/S

#103 fix: change log platform to string
  third/third.pb.go
  third/third.proto
Labels: size/XS

#104 feat: update conversation fields and update pb files.
  auth/auth.pb.go
  conversation/conversation.pb.go
  conversation/conversation.proto
  errinfo/errinfo.pb.go
  group/group.pb.go
  msg/msg.pb.go
  msggateway/msggateway.pb.go
  push/push.pb.go
  relation/relation.pb.go
  rtc/rtc.pb.go
  sdkws/sdkws.pb.go
  statistics/statistics.pb.go
  third/third.pb.go
  user/user.pb.go
  wrapperspb/wrapperspb.pb.go
Labels: size/M

#105 update ConversationsDestructMsgs method.
  conversation/conversation.pb.go
  conversation/conversation.proto
Labels: size/XS
