Repository openimsdk/protocol, pull requests merged in 2024-08, with the labels that each got.

#106 update conversation and msg destruct pb.
  conversation/conversation.pb.go
  conversation/conversation.proto
  msg/msg.pb.go
  msg/msg.proto
Labels: size/S

#108 fix: notification msg type check
  sdkws/sdkws.go
Labels: size/XS

#109 fix: merge member invited tips into member enter tips
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
Labels: size/S

#110 fix: change name
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
Labels: size/XS

#111 feat: conversation set min seq
  conversation/conversation.pb.go
  conversation/conversation.proto
Labels: size/XS

#112 feat: update GroupInfoForSetEX struct.
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
Labels: size/L

#114 update group pb.
  conversation/conversation.pb.go
  group/group.pb.go
  group/group.proto
Labels: size/XS

#115 revert: change name
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
Labels: size/S

#116 feat: SetUserConversationsMinSeq
  msg/msg.pb.go
  msg/msg.proto
Labels: size/S

#117 feat: change userID to userIDs
  msg/msg.pb.go
  msg/msg.proto
Labels: size/XS
