Repository openimsdk/protocol, pull requests merged in 2024-12, with the labels that each got.

#164 fix: update destrcut and clear msg.
  msg/msg.pb.go
  msg/msg.proto
Labels: size/XS

#165 build: rename destruct to clear.
  conversation/conversation.pb.go
  conversation/conversation.proto
  conversation/conversation_grpc.pb.go
Labels: size/XS

#166 feat: change UploadLogsReq
  third/third.pb.go
  third/third.proto
Labels: size/XS

#167 feat: fetch messages add minSeq when message isEnd is true.
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
Labels: size/XS

#168 feat: fetch messages add minSeq when message isEnd is true.
  msg/msg.pb.go
  msg/msg.proto
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
Labels: size/XS

#169 feat: gen rpc_caller magefile
  README.md
  auth/auth_caller.go
  conversation/conversation_caller.go
  group/group_caller.go
  magefile.go
  msg/msg_caller.go
  msggateway/msggateway_caller.go
  push/push_caller.go
  relation/relation_caller.go
  rpccall/caller.go
  rtc/rtc_caller.go
  third/third_caller.go
  user/user_caller.go
Labels: size/XL

#170 feat: gen rpc
  rpccall/caller.go
Labels: size/S

#172 Fix gen
  magefile.go
  msg/msg_caller.go
Labels: size/M

#173 fix: gen proto
  rpccall/caller.go
Labels: size/S

#171 fix: magefile typo
  magefile.go
Labels: size/XS
