Repository openimsdk/protocol, pull requests merged in 2024-01, with the labels that each got.

#56 fix: del the searchMessage Check
  msg/msg.go
Labels: size/XS

#58 fix: add a keywork field in group/get_groups api req
  group/group.pb.go
  group/group.proto
Labels: size/XS

#59 add usercommand add, delete, and update
  constant/constant.go
  conversation/conversation.pb.go
  group/group.pb.go
  msg/msgv3.pb.go
  sdkws/sdkws.pb.go
  sdkws/sdkws.proto
  user/user.go
  user/user.pb.go
  user/user.proto
Labels: size/M

#60 fix: fix the addNotificationReq adn searchNotificationReq
  user/user.pb.go
  user/user.proto
Labels: size/S

#61 fix: add a IMOrdinaryUser
  constant/constant.go
Labels: size/XS

#62 fix: fix the GetSortedConversationList req and resp
  conversation/conversation.go
  conversation/conversation.pb.go
  conversation/conversation.proto
  user/user.go
Labels: size/M

#63 able to search with keyword in get_users
  conversation/conversation.pb.go
  user/user.pb.go
  user/user.proto
Labels: size/XS

#64 fix: remove filed of recvID in msggateway pb protocol.
  msggateway/msggateway.pb.go
  msggateway/msggateway.proto
Labels: size/XS
